### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by mika76** [saltyquark/vue-identity#2]
When I click authenticate, the following happens.
![screen shot 2017-03-21 at 13 42 43](https://cloud.githubusercontent.com/assets/229311/24145977/52ba3e2c-0e3c-11e7-85ca-d6109c5c7fb1.png)

- cloned repo
- ran yarn
- ran yarn run build
- ran yarn run dev
- went to http://localhost:8080 - clicked on authenticate

**Comment by mattfroese** [comment]
Yes, the example did not have a very great sample to work against. 

In `0.0.6`, I have included a sample node server with a working version. Hope that helps!
